import { DemoPreset, DemoPresetId, VaultDocument } from '../types/vault.ts';

export const DEMO_PRESETS: Record<DemoPresetId, DemoPreset> = {
  STANFORD_VALID: {
    id: 'STANFORD_VALID',
    name: 'Stanford Valid',
    universityName: 'Stanford University',
    tagline: 'Valid Student ID & Schedule',
    badge: 'Standard Flow',
    description: 'Stanford undergraduate with valid 2025-2026 Student ID card and Fall 2026 class schedule.',
    testScenario: 'Full verification workflow with pre-signed document upload.',
    profile: {
      presetId: 'STANFORD_VALID',
      firstName: 'Alex',
      lastName: 'Chen',
      fullName: 'Alex Chen',
      email: 'alex.chen@stanford.edu',
      birthDate: '2003-04-15',
      universityId: 'sch_stanford_002',
      universityName: 'Stanford University',
      academicLevel: 'UNDERGRADUATE',
      graduationYear: 2026,
      studentIdNumber: 'SU-2026-9481',
    },
    documents: [
      {
        id: 'doc_stan_id_2026',
        title: 'Stanford Student ID Card (2025-2026)',
        fileName: 'stanford_id_2026.png',
        docType: 'STUDENT_ID',
        mimeType: 'image/png',
        fileSizeBytes: 245760,
        issueDate: '2025-09-01',
        expirationDate: '2026-06-30',
        isValid: true,
        isIllegible: false,
        description: 'Official high-resolution student ID card with valid active academic year.',
        previewText: 'STANFORD UNIVERSITY | Alex Chen | ID: SU-2026-9481 | Valid: 2025-2026',
      },
      {
        id: 'doc_stan_schedule_2026',
        title: 'Fall 2026 Registered Class Schedule',
        fileName: 'stanford_schedule_2026.pdf',
        docType: 'CLASS_SCHEDULE',
        mimeType: 'application/pdf',
        fileSizeBytes: 184320,
        issueDate: '2026-09-01',
        expirationDate: '2026-12-18',
        isValid: true,
        isIllegible: false,
        description: 'Registrar signed course schedule: CS 229, CS 224N, STATS 214 (15 Units).',
        previewText: 'STANFORD REGISTRAR | Fall 2026 Schedule | Alex Chen | CS 229, CS 224N',
      },
    ],
  },

  HARVARD_EXPIRED: {
    id: 'HARVARD_EXPIRED',
    name: 'Harvard Expired',
    universityName: 'Harvard University',
    tagline: 'Expired ID + Valid Tuition Bill',
    badge: 'Date Recovery',
    description: 'Harvard undergraduate with expired 2023-2024 Student ID and valid Fall 2026 tuition bill for testing automated date recovery.',
    testScenario: 'EXPIRED_DOCUMENT rejection triggers automated recovery via tuition receipt.',
    profile: {
      presetId: 'HARVARD_EXPIRED',
      firstName: 'Maya',
      lastName: 'Patel',
      fullName: 'Maya Patel',
      email: 'maya.patel@harvard.edu',
      birthDate: '2002-11-20',
      universityId: 'sch_harvard_003',
      universityName: 'Harvard University',
      academicLevel: 'UNDERGRADUATE',
      graduationYear: 2026,
      studentIdNumber: 'HU-2024-3829',
    },
    documents: [
      {
        id: 'doc_harv_id_2024',
        title: 'Harvard Student ID (Expired 2023-2024)',
        fileName: 'harvard_id_2024.png',
        docType: 'STUDENT_ID',
        mimeType: 'image/png',
        fileSizeBytes: 212992,
        issueDate: '2023-09-01',
        expirationDate: '2024-05-31',
        isValid: false,
        isIllegible: false,
        description: 'Expired student ID card from sophomore year (Expired: May 31, 2024).',
        previewText: 'HARVARD COLLEGE | Maya Patel | ID: HU-2024-3829 | EXPIRED: MAY 2024',
      },
      {
        id: 'doc_harv_tuition_2026',
        title: 'Fall 2026 Official Tuition Receipt',
        fileName: 'harvard_tuition_2026.pdf',
        docType: 'TUITION_RECEIPT',
        mimeType: 'application/pdf',
        fileSizeBytes: 307200,
        issueDate: '2026-08-15',
        expirationDate: '2026-12-31',
        isValid: true,
        isIllegible: false,
        description: 'Official Bursar receipt confirming paid Fall 2026 tuition balance.',
        previewText: 'HARVARD BURSAR OFFICE | Fall 2026 Statement | Maya Patel | Paid: $28,450',
      },
    ],
  },

  BERKELEY_ILLEGIBLE: {
    id: 'BERKELEY_ILLEGIBLE',
    name: 'Berkeley Illegible',
    universityName: 'University of California, Berkeley',
    tagline: 'Blurry Scan + Valid Transcript',
    badge: 'Quality Recovery',
    description: 'UC Berkeley undergraduate with low-res blurry scan and valid official transcript for testing image quality recovery.',
    testScenario: 'ILLEGIBLE_DOCUMENT rejection triggers automated recovery via PDF transcript.',
    profile: {
      presetId: 'BERKELEY_ILLEGIBLE',
      firstName: 'Jordan',
      lastName: 'Lee',
      fullName: 'Jordan Lee',
      email: 'jordan.lee@berkeley.edu',
      birthDate: '2004-01-10',
      universityId: 'sch_berkeley_004',
      universityName: 'University of California, Berkeley',
      academicLevel: 'UNDERGRADUATE',
      graduationYear: 2027,
      studentIdNumber: 'UCB-3038-1920',
    },
    documents: [
      {
        id: 'doc_berk_blurry_id',
        title: 'Cal 1 Card (Low-Res Blurry Photo)',
        fileName: 'berkeley_blurry_id.jpg',
        docType: 'STUDENT_ID',
        mimeType: 'image/jpeg',
        fileSizeBytes: 98304,
        issueDate: '2025-09-01',
        expirationDate: '2027-05-31',
        isValid: false,
        isIllegible: true,
        description: 'Blurry low-light camera photo failing OCR text readability thresholds.',
        previewText: 'UC BERKELEY [BLURRY/UNREADABLE OCR] | Jordan Lee | Cal 1 Card',
      },
      {
        id: 'doc_berk_transcript_2026',
        title: 'UC Berkeley Official Academic Transcript',
        fileName: 'berkeley_transcript_2026.pdf',
        docType: 'TRANSCRIPT',
        mimeType: 'application/pdf',
        fileSizeBytes: 419840,
        issueDate: '2026-08-20',
        expirationDate: '2027-05-31',
        isValid: true,
        isIllegible: false,
        description: 'Official cryptographically signed transcript with current enrollment verification.',
        previewText: 'OFFICIAL ACADEMIC RECORD | UC Berkeley | Jordan Lee | Enrolled: Full Time',
      },
    ],
  },

  MIT_INSTANT: {
    id: 'MIT_INSTANT',
    name: 'MIT Instant',
    universityName: 'Massachusetts Institute of Technology',
    tagline: 'Instant Registrar Match',
    badge: 'Instant Match',
    description: 'MIT graduate student eligible for instant registrar match bypassing document upload.',
    testScenario: 'Instant verification approval without entering docUpload step.',
    profile: {
      presetId: 'MIT_INSTANT',
      firstName: 'Marcus',
      lastName: 'Vance',
      fullName: 'Marcus Vance',
      email: 'marcus.vance@mit.edu',
      birthDate: '2000-08-22',
      universityId: 'sch_mit_001',
      universityName: 'Massachusetts Institute of Technology',
      academicLevel: 'GRADUATE',
      graduationYear: 2026,
      studentIdNumber: 'MIT-9082-4112',
    },
    documents: [
      {
        id: 'doc_mit_id_2026',
        title: 'MIT Graduate Student ID Card',
        fileName: 'mit_id_2026.png',
        docType: 'STUDENT_ID',
        mimeType: 'image/png',
        fileSizeBytes: 262144,
        issueDate: '2025-09-01',
        expirationDate: '2026-12-31',
        isValid: true,
        isIllegible: false,
        description: 'Valid MIT Graduate identification card for Department of EECS.',
        previewText: 'MIT EECS GRADUATE | Marcus Vance | ID: MIT-9082-4112 | Exp: 2026',
      },
    ],
  },
};

/**
 * Creates synthetic binary Blob payloads for sandboxed mock documents.
 */
export function createMockDocumentBlob(doc: VaultDocument): Blob {
  const content = `MOCK_BINARY_DATA::${doc.id}::${doc.docType}::${doc.fileName}::${doc.previewText || doc.title}`;
  return new Blob([content], { type: doc.mimeType });
}
